# Generated by Django 2.0.3 on 2018-03-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColourCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolour_one', models.CharField(max_length=7)),
                ('bgcolour_two', models.CharField(max_length=7)),
                ('textcolour_one', models.CharField(max_length=7)),
                ('textcolour_two', models.CharField(max_length=7)),
            ],
        ),
    ]
