# Generated by Django 2.0.3 on 2018-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourcombo',
            name='bgcolour_one',
            field=models.CharField(default='#FF5733', max_length=7),
        ),
        migrations.AlterField(
            model_name='colourcombo',
            name='bgcolour_two',
            field=models.CharField(default='#E58571', max_length=7),
        ),
        migrations.AlterField(
            model_name='colourcombo',
            name='textcolour_one',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='colourcombo',
            name='textcolour_two',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
