# Generated by Django 2.0.3 on 2018-03-14 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20180313_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourcombo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colourcombo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
